name: CMake Build for All Services

on:
  push:
    branches: [ "main" , "feature/api"]
  pull_request:
    branches: [ "main" , "feature/api"]

env:
  BUILD_TYPE: Release

jobs:
  build-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, catalog, streaming, api]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create build directory for ${{ matrix.service }}
        run: mkdir -p server/build-${{ matrix.service }}

      - name: Configure CMake for ${{ matrix.service }}
        run: |
          cmake \
            -B server/build-${{ matrix.service }} \
            -S server/src/${{ matrix.service }} \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DCMAKE_PREFIX_PATH=${{ github.workspace }}/server

      - name: Build ${{ matrix.service }}
        run: |
          cmake --build server/build-${{ matrix.service }} --config ${{ env.BUILD_TYPE }}

      - name: Verify artifact for ${{ matrix.service }}
        # можно проверять, что исполняемый файл создан, например:
        run: |
          if [ ! -f server/build-${{ matrix.service }}/${{ matrix.service }} ]; then
            echo "Build artifact not found for ${{ matrix.service }}"
            exit 1
          fi