name: Docker Build, Test, then Publish

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - feature/api
  pull_request:
    branches:
      - main
      - feature/api

env:
  IMAGE_PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}/yourmusic

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build auth image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/src/auth/Dockerfile
          push: false
          load: true
          tags: ${{ env.IMAGE_PREFIX }}-auth:latest

      - name: Build catalog image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/src/catalog/Dockerfile
          push: false
          load: true
          tags: ${{ env.IMAGE_PREFIX }}-catalog:latest

      - name: Build streaming image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/src/streaming/Dockerfile
          push: false
          load: true
          tags: ${{ env.IMAGE_PREFIX }}-streaming:latest

      - name: Build api image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/src/api/Dockerfile
          push: false
          load: true
          tags: ${{ env.IMAGE_PREFIX }}-api:latest

      - name: Test auth container
        run: |
          docker run -d --name auth-test -p 8082:8082 ${{ env.IMAGE_PREFIX }}-auth:latest
          until curl -s http://localhost:8082/health; do sleep 1; done
          echo "Auth OK"
          docker rm -f auth-test

      - name: Test catalog container
        run: |
          docker run -d --name catalog-test -p 8083:8083 ${{ env.IMAGE_PREFIX }}-catalog:latest
          until curl -s http://localhost:8083/health; do sleep 1; done
          echo "Catalog OK"
          docker rm -f catalog-test

      - name: Test streaming container
        run: |
          docker run -d --name streaming-test -p 8084:8084 ${{ env.IMAGE_PREFIX }}-streaming:latest
          until curl -s http://localhost:8084/health; do sleep 1; done
          echo "Streaming OK"
          docker rm -f streaming-test

      - name: Test api container
        run: |
          docker run -d --name api-test -p 8080:8080 \
            -e AUTH_HOST=auth-test -e AUTH_PORT=8082 \
            -e CATALOG_HOST=catalog-test -e CATALOG_PORT=8083 \
            -e STREAMING_HOST=streaming-test -e STREAMING_PORT=8084 \
            ${{ env.IMAGE_PREFIX }}-api:latest
          until curl -s http://localhost:8080/health; do sleep 1; done
          echo "API OK"
          docker rm -f api-test

      - name: Push auth image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/src/auth/Dockerfile
          push: true
          tags: ${{ env.IMAGE_PREFIX }}-auth:latest

      - name: Push catalog image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/src/catalog/Dockerfile
          push: true
          tags: ${{ env.IMAGE_PREFIX }}-catalog:latest

      - name: Push streaming image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/src/streaming/Dockerfile
          push: true
          tags: ${{ env.IMAGE_PREFIX }}-streaming:latest

      - name: Push api image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/src/api/Dockerfile
          push: true
          tags: ${{ env.IMAGE_PREFIX }}-api:latest
